name: Deploy App1

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Select branch to deploy'
        required: true
        default: 'main'
      deployment-environment:   # GitHub environment for approval
        description: 'Select GitHub Environment for approval'
        required: true
        type: choice
        default: 'app1-test'
        options:
          - app1-test
          - app1-prod
          - app2-test
          - app2-prod
      slot-name:               # Azure deployment slot
        description: 'Select deployment slot'
        required: true
        type: choice
        default: staging
        options:
          - staging
          - production

jobs:
  deploy-app1:
    uses: ./.github/workflows/Reusable-workflow.yml
    with:
      app-name: app1
      environment: ${{ github.event.inputs.deployment-environment }}   # Approval environment
      slot-name: ${{ github.event.inputs.slot-name }}                  # Azure deployment slot
      node-version: 18.x
      app-location: app1/frontend
      output-location: build
    secrets: inherit
