name: Deploy App1

on:
  workflow_dispatch:
    inputs:
      slot-name:
        description: |
          Azure deployment slot:
          - Leave empty → deploy to Production slot
          - Enter "staging", "test", or any custom name → deploy to a custom slot
          - Approval is required for all deployments
        required: false
        default: ""
      environment:
        description: |
          GitHub Environment for approval:
          - Choose the environment corresponding to this deployment
          - Approval is required before deployment proceeds
        required: true
        type: choice
        options:
          - app1-test
          - app1-prod
          - app2-test
          - app2-prod

jobs:
  deploy-app1:
    uses: ./.github/workflows/Reusable-workflow.yml
    with:
      slot-name: ${{ github.event.inputs.slot-name }}
      environment: ${{ github.event.inputs.environment }}
      app-name: app1
      node-version: 18.x
      app-location: app1/frontend
      output-location: build
    secrets: inherit
