name: Deploy App1

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Select branch to deploy'
        required: true
        default: 'main'
      deployment-environment:
        description: 'Select GitHub environment for approval'
        required: true
        type: choice
        default: 'app1-test'
        options:
          - app1-test
          - app1-prod
          - app2-test
          - app2-prod

jobs:
  deploy-app1:
    uses: ./.github/workflows/Reusable-workflow.yml
    with:
      app-name: app1
      node-version: 18.x
      app-location: app1/frontend
      output-location: build
      branch: ${{ github.event.inputs.branch }}
      slot-name: ${{ github.event.inputs.branch == 'main' && 'production' || 'staging' }}
      environment: ${{ github.event.inputs.deployment-environment }}
    secrets: inherit
