name: Deploy App1

on:
  workflow_dispatch:
    inputs:
      slot-name:
        description: "Enter the slot to deploy: leave empty for Production (requires approval), or specify a slot like staging/test for direct deployment."
        required: false
        default: ""
      deployment-environment:
        description: "Select GitHub Environment (used only if deploying to Production)"
        required: true
        type: choice
        default: "app1-test"
        options:
          - app1-test
          - app1-prod
          - app2-test
          - app2-prod

jobs:
  deploy-app1:
    uses: ./.github/workflows/Reusable-workflow.yml   # path to your reusable workflow
    with:
      app-name: app1
      environment: ${{ github.event.inputs.deployment-environment }}
      slot-name: ${{ github.event.inputs.slot-name }}
      node-version: 18.x
      app-location: app1/frontend
      output-location: build
    secrets: inherit
