name: Deploy App1

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Select branch to deploy'
        required: true
        default: 'main'
      deployment-environment:
        description: 'Select GitHub Environment for approval'
        required: true
        default: 'app1-test'
        type: choice
        options:
          - app1-test
          - app1-prod
          - app2-test
          - app2-prod


jobs:
  deploy-app1:
    uses: ./.github/workflows/Reusable-workflow.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      app-name: app1
      environment: app1-test   # Approval environment set in GitHub
      node-version: 18.x
      app-location: app1/frontend
      output-location: build

    secrets: inherit
