name: Reusable Static Web App Deployment

on:
  workflow_call:
    inputs:
      app-name:
        required: true
        type: string
      environment:       # GitHub Environment for approvals (Prod only)
        required: true
        type: string
      slot-name:         # Azure deployment slot: staging/test/etc (empty = Production)
        required: false
        type: string
        default: ""      # Default empty → means Production
      node-version:
        required: true
        type: string
      app-location:
        required: true
        type: string
      output-location:
        required: true
        type: string
      branch:
        required: false
        type: string
        default: ${{ github.ref_name }}

jobs:
  validate:
    name: Validate & Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install Dependencies
        run: npm install
        working-directory: ${{ inputs.app-location }}

      - name: Lint Application
        run: npm run lint
        working-directory: ${{ inputs.app-location }}

      - name: Run Tests
        run: npm test
        working-directory: ${{ inputs.app-location }}

      - name: Build Application
        run: npm run build
        working-directory: ${{ inputs.app-location }}

  approve:
    name: Await Prod Approval
    needs: validate
    if: ${{ inputs.slot-name == '' }}   # Run approval ONLY if Production
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}   # Requires GitHub env approval
    steps:
      - name: Approval Message
        run: | 
          echo "⏳ Awaiting approval for ${{ inputs.app-name }} to deploy to Production slot"

  deploy:
    name: Deploy to Azure Static Web App
    needs: 
      - validate
      - ${{ inputs.slot-name == '' && 'approve' || '' }}   # Add approval only if prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: ${{ inputs.app-location }}
          output_location: ${{ inputs.output-location }}
          deployment_environment: ${{ inputs.slot-name != '' && inputs.slot-name || 'Production' }}

      - name: Deployment Info
        run: | 
          echo "✅ Deployed ${{ inputs.app-name }} to slot: ${{ inputs.slot-name != '' && inputs.slot-name || 'Production' }}"
