name: Reusable Static Web App Deployment

on:
  workflow_call:
    inputs:
      app-name:
        required: true
        type: string
      environment:       # GitHub Environment for approvals
        required: true
        type: string
      slot-name:         # Azure deployment slot: staging/test/etc (empty = Production)
        required: false
        type: string
        default: ""      # Empty → means Production
      node-version:
        required: true
        type: string
      app-location:
        required: true
        type: string
      output-location:
        required: true
        type: string

jobs:
  validate:
    name: Validate & Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install Dependencies
        run: npm install
        working-directory: ${{ inputs.app-location }}

      - name: Lint Application
        run: npm run lint
        working-directory: ${{ inputs.app-location }}

      - name: Run Tests
        run: npm test
        working-directory: ${{ inputs.app-location }}

      - name: Build Application
        run: npm run build
        working-directory: ${{ inputs.app-location }}

  approve:
    name: Await Deployment Approval
    needs: validate
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Approval Message
        run: echo "⏳ Awaiting approval for ${{ inputs.app-name }} to deploy to slot: '${{ inputs.slot-name != '' && inputs.slot-name || 'Production' }}'"

  deploy:
    name: Deploy to Azure Static Web App
    needs: [validate, approve]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: ${{ inputs.app-location }}
          output_location: ${{ inputs.output-location }}
          # Use slot-name if provided, otherwise deploy to Production
          deployment_environment: ${{ inputs.slot-name != '' && inputs.slot-name || 'Production' }}

      - name: Deployment Info
        run: |
          SLOT="${{ inputs.slot-name }}"
          if [ -z "$SLOT" ]; then
            SLOT="Production"
          fi
          echo "✅ Deployed to slot: $SLOT"
